### PR TITLE
Update tty.c

### PR DESCRIPTION
**Pull request by ayan312002**
Adding carriage return and backspace to tty.c :D (we need backspace.. don't we?)

### CODE REVIEW

**Comment by DaGamingBoss** [comment]
I will accept it, but some things will be modified because it doesn't work properly. You never call tty_update_cursor() and the terminal_column = 0 line overwrite the little header thingy on the shell.

**Comment by ayan312002** [comment]
Yep I agree.. the code is not that good.. You should change u according to your needs.. At least we can avoid getting the  weird artifacts on calling \n

**Comment by DaGamingBoss** [comment]
Have you built the toolchain yet?

**Comment by ayan312002** [comment]
Nope..

**Pull request merged**
