### PR TITLE
Update tty.cpp..

### PR DESCRIPTION
**Pull request by ayan312002**
Added carriage return, and backspace..

### CODE REVIEW

**Comment by ayan312002** [comment]
I have updated the terminal but make sure to compile it because i have not compiled it yet..

**Comment by DaGamingBoss** [comment]
Thanks alot! I have posted the instructions to compile on doc/Compilation.txt. Also i'm in the process of porting it to C instead of C++ if you don't mind.

**Comment by DaGamingBoss** [comment]
Oh and don't change the x86_64 arch directory, it's just a stub. Change i386 instead... :+1:

**Comment by ayan312002** [comment]
You read my mind.. I'm not comfortable with c++ so yep porting it to c will be a good idea.. And OK I didn't knew that x86 thing.. Thanks..

**Pull request merged**
